#cloud-config
package_update: true
packages:
  - emacs
  - build-essential 
  - ack 
  - zlib1g-dev 
  - libssl-dev 
  - libncurses-dev 
  - libbz2-dev 
  - libffi-dev 
  - libreadline-dev 
  - libsqlite3-dev 
  - liblzma-dev 
  - locales
  - libodbc2
  - libgl1
  - libegl1

locale: en_US

runcmd:
  - sudo locale-gen en_US.UTF-8
  - sudo update-locale LANG=en_US.UTF-8
  - curl -fsSL https://pyenv.run | bash
  - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
  - echo 'export [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
  - echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc
  - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
  - echo 'export [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile
  - echo 'eval "$(pyenv init - bash)"' >> ~/.profile
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
